server:
  port: 8888

spring:
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gggeon96/cherry-config.git
          username: geon1120@gmail.com
          password: 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

management:
  endpoints:
    web:
      exposure:
        include: '*'
