server:
  port: 8088

spring:
  application:
    name: notice-service

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tandamzi_notice?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

vapid:
  key:
    public: BPLTvXapXtft3HhPpDxRPiY5OHWtFMEMP160FHqoojQpIPc1EZL77A_CcBMF7bhBQfP5kWv-5DbSiUlUK9BVWzQ
    private: 3E7oD3n3YwKbJdH_L2f6boy7rgaNlPGkdsyUzN1h5c8

logging:
  level:
    org:
      hibernate:
        SQL: debug
