import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const Layout = ({ children }) => {
  return (
    <div>
      <div>test</div>
      {children}
    </div>
  );
};

export default Layout;
